-- CreateTable
CREATE TABLE "Location" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "phone" TEXT,
    "acquiredAt" DATETIME,
    "facilityType" TEXT NOT NULL,
    "serviceBoarding" BOOLEAN NOT NULL DEFAULT false,
    "serviceDaycare" BOOLEAN NOT NULL DEFAULT false,
    "serviceGrooming" BOOLEAN NOT NULL DEFAULT false,
    "serviceTraining" BOOLEAN NOT NULL DEFAULT false,
    "serviceVetCare" BOOLEAN NOT NULL DEFAULT false,
    "serviceGroomingEd" BOOLEAN NOT NULL DEFAULT false,
    "serviceWebcams" BOOLEAN NOT NULL DEFAULT false,
    "serviceMobileGroom" BOOLEAN NOT NULL DEFAULT false,
    "serviceRetail" BOOLEAN NOT NULL DEFAULT false,
    "currentUrl" TEXT,
    "currentPlatform" TEXT,
    "currentTechStack" TEXT,
    "lighthousePerf" INTEGER,
    "lighthouseA11y" INTEGER,
    "lighthouseSEO" INTEGER,
    "lighthouseBP" INTEGER,
    "lighthouseAudited" DATETIME,
    "googleRating" REAL,
    "googleReviewCount" INTEGER,
    "rebuildStatus" TEXT NOT NULL DEFAULT 'not-scoped',
    "rebuildTemplate" TEXT,
    "previewUrl" TEXT,
    "targetLaunchDate" DATETIME,
    "liveUrl" TEXT,
    "needsOnlineBooking" BOOLEAN NOT NULL DEFAULT false,
    "needsWebcamFeed" BOOLEAN NOT NULL DEFAULT false,
    "needsPricingCalculator" BOOLEAN NOT NULL DEFAULT false,
    "needsStaffPage" BOOLEAN NOT NULL DEFAULT false,
    "needsServicePages" BOOLEAN NOT NULL DEFAULT false,
    "needsPhotoGallery" BOOLEAN NOT NULL DEFAULT false,
    "needsContactForm" BOOLEAN NOT NULL DEFAULT false,
    "needsMapsEmbed" BOOLEAN NOT NULL DEFAULT false,
    "needsReviewsWidget" BOOLEAN NOT NULL DEFAULT false,
    "domainRegistrar" TEXT,
    "dnsProvider" TEXT,
    "nameservers" TEXT,
    "hostingProvider" TEXT,
    "emailPlatform" TEXT,
    "mxStatus" TEXT,
    "spfStatus" TEXT,
    "dkimStatus" TEXT,
    "infraNotes" TEXT,
    "secondaryDomain" TEXT,
    "secondaryDomainNotes" TEXT,
    "migrationStatus" TEXT NOT NULL DEFAULT 'not-started',
    "migrationBlockedBy" TEXT,
    "migrationNotes" TEXT,
    "hasLogoVector" BOOLEAN NOT NULL DEFAULT false,
    "hasLogoRaster" BOOLEAN NOT NULL DEFAULT false,
    "hasBrandColors" BOOLEAN NOT NULL DEFAULT false,
    "hasPhotography" TEXT NOT NULL DEFAULT 'none',
    "assetNotes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Contact" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "locationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "role" TEXT NOT NULL,
    "company" TEXT,
    "notes" TEXT,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Contact_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Note" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "locationId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "author" TEXT NOT NULL DEFAULT 'Mike',
    "isBlocker" BOOLEAN NOT NULL DEFAULT false,
    "isResolved" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Note_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Location_slug_key" ON "Location"("slug");
